version: "3.8"

services:
  nginx:
    build: req/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: req/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - inception_network

  mariadb:
    build: ./req/mariadb/
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_network
      
volumes:
  wp_volume:
     driver: local
     driver_opts:
       type: volume
       device: /Users/jaeywon/inception2/inception/srcs/req/volume
       o: bind

networks:
  inception_network:
    driver: bridge